<?php
/**
 *  2Moons 
 *   by Jan-Otto Kröpke 2009-2016
 *
 * For the full copyright and license information, please view the LICENSE
 *
 * @package 2Moons
 * @author Jan-Otto Kröpke <slaver7@gmail.com>
 * @copyright 2009 Lucky
 * @copyright 2016 Jan-Otto Kröpke <slaver7@gmail.com>
 * @licence MIT
 * @version 1.8.0
 * @link https://github.com/jkroepke/2Moons
 */
// Translated into English by QwataKayean . All rights reversed (C) 2012
// 2Moons - Copyright (C) 2010-2012 Slaver
$LNG['faq_overview']	= "FAQ";
 
$LNG['questions']					= array();
$LNG['questions'][1]['category']	= 'Tips for beginners';
$LNG['questions'][1][1]['title']	= 'Step 1';
$LNG['questions'][1][1]['body']		= <<<BODY
<p>This part of the Tutorial describes the main buildings of the game. It advises about what to build at the beginning, and what do you need to build a successful Empire.</p>
<h3>Solar plant:</h3>
<p>The Solar Plant generates energy, which is used to produce the three main resources. For this production to actually happen, the energy used in production cannot exceed the energy generated by the plant. When the production mix exceeds the available energy, the Energy numbers in the menu turn red. This has to be avoided.</p>
<h3>Metal mine:</h3>
<p>Metal is one of the three main resources available in the game. It is used for almost anything you can build or research. Therefore, a good expansion of the metal mine is advisable.</p>
<h3>Crystal mine and Deuterium synthesizer</h3>
<p>Crystal is highly used for buildings, ships, and research. It is produced to a lesser extent than metal, which makes it more expensive.
   Deuterium is a source of energy, highly used as fuel for ships.</p>
BODY;
$LNG['questions'][1][2]['title']	= 'Step 2';
$LNG['questions'][1][2]['body']		= <<<BODY
<p>To expand your Empire and compete with other players you need to interact with other buildings aswell. Through the research and construction of a Hangar to begin construction of your Fleet and Planetary Defense. Details can be found here:</p>
<h3>The Hangar:</h3>
<p>Here are all the ships that you have available in the game. Some ships will have higher technological requirements to be built. An overview of the ships or defence which has technological requirements can be found under the title "technology" in the menu. Leveling up the Shipyard enables you faster construction of your ships and defences.</p>
<h3>The Recearch Lab:</h3>
<p>These are used to construct new buildings, ships and defenses. Also the researches can be used to get some bonuses. The research can be accelerated through the expansion of the Research Lab</p>
<h3>Robot Factory:</h3>
<p>The Robot Factory is an essential component. Through its expansion, construction time of buildings gets reduced.</p>
BODY;
$LNG['questions'][1][3]['title']	= 'Step 3';
$LNG['questions'][1][3]['body']		= <<<BODY
<p>This part of the tutorial is dedicated to defending the planet and first actions with your own fleet.</p>
<h3>Galaxy view:</h3>
<p>It is used to find other players. You will find detailed information on other planets, and also you can send your fleet directly from this point of view. Besides that, you can contact other players, or if you posses Spy Probes you can even spy their planets.</p>
<h3>Sending Fleets:</h3>
<p>You can send your fleet directly from the Galaxy view or by going to "Fleets" tab. First step is to select a nuber of certain types of ships you wish to send on a mission. Second step is entering the coordinates (that you obtained from the Galaxy view) and selecting the speed at which your fleet will be flying. Last step is selecting an action you want to perform with your fleet, such as "Attack", "Colonize", "Transfer", "Transport" or "Deploy" etc.</p>
<h3>The Defense:</h3>
<p>To be able to protect your own planet besides your fleet you need to build some defense. These offer some protection against the enemies fleet at the moment of attack. In contrast to the fleet, 70% of destroyed defence gets repaired</p>
BODY;
$LNG['questions'][2]['category']	= 'Advanced Tips';
$LNG['questions'][2][1]['title']	= 'Raid';
$LNG['questions'][2][1]['body']		= <<<BODY
<h3>Raids:</h3>
<p>A raid is an attack on another players planet undertaken in order to acquire their resources. If an attack is successful, up to 50% of the resources on the target planet may be taken by the attacking fleet as plunder. There are several types of attacks such as</p>:
<ul>
<li>Inactive Raids</li>
<li>ACS(Alliance Combat System)</li>
<li>Intercepting a fleet</li>
</ul>
<h3>Inactive Raids:</h3>
<p>As a fleeter you basically want to make resources as fast and easy as possible. Sometimes won't be able to attack any active players around you as most of them 
will be online or already fleet saving. However, you can raid inactive players as they are not likely to come online. Farming inactives is not as suspenseful as
attacking active players however it is a good way of working around time consuming attacks</p>
<h3>ACS:</h3>
<p>The Alliance Combat System (or ACS) allows for friends and alliance members to temporarily combine their fleets to attack or defend a target that either might not have been able to attack or defend alone. An Alliance Depot is not a prerequisite to attack or defend a planet with ACS</p>
<h3>Intercepting a fleet:</h3>
<p>This is where it gets tricky. How do I find possible targets? You basically try to find them like idling fleets, however every time you see that fleet you
notice that the player is online. Before you can crash someone who is saving and watching his fleet you have to find out how, when and where the player is 
saving his fleet. To do that you have to observe the player. If the player is saving without moons its easier to intercept him as you can basically rely on 
your phalanx alone. But when it comes to intercepting fleets saved from a moon it gets time consuming. Depending on how the player saves you have to destroy 
his moon(s) to be able to phalanx his fleet.</p>
BODY;
$LNG['questions'][2][2]['title']	= 'Fleetsave';
$LNG['questions'][2][2]['body']		= <<<BODY
<h3>How can I protect myself</h3>
<p>A large number of weapons of Defense scares some players already unfortunately, and are lured by others. As a result, you lose a lot of features, once defenses, nothing goes to the field of destruction, when they are destroyed. The only exception is the so-called destruction of defences, in which the attacker when te attacks, creates the destruction defenses on destruction (7% loss of defence not destruction account, account is the total loss of the defense in combat).</p>
<p>Additionally, there is the Interplanetery Missile, whose only aim is to destroy the defense. In contrast with the normal attack, the missiles are not again built. A well-planned attack, with several interplanetÃ missile reduces the danger at your own fleet considerably.</p>
<p>The increase in espionage research allows an increase to be able to see the contents of the other players. Thus, while this number is high, will s access to ships, defence, buildings or researches of the enemy</p>
<p>The best way of protection is no player see what you have in reality, during the time that does not have access to the Internet and they run a fleet. If the enemy attack, stole only the resources produced that was not taken by the fleet, which contributes to the enemy judging that is weak and thus avoids s probability he attack you</p>
<h3>OGame "Fleet Save"</h3>
<p>The Fleetsave of the fleet is a key component of OGame, but unfortunately a lot of players don't understand Fleetsaving. So here's an explanation: there are many ways to its resources and its fleet of more or less secure to protect against the attacks of enemy fleets. Here are some of the almost 100% sure, but others are very uncertain.<br>The first method of Fleetsaves is "findand callback". This sends the player's fleet to a planet in your own area with the Mission of transfer. This video ´ will then stop after awhile. This is used for calculation in which the player makes Phalanx accounts related to the enemy fleet, with his time of combat. This method is not 100% sure, but if you don't you break on the final point, but a couple of hours before, just with a huge effort to intercept.<br>Note-many players "intelligent" doesn't manage to extract the Defender appear on, or returning to the fleet in flight!</p>
<p>A very common method of Fleetsave is sending a fleet and resources of a moon, and send to a destruction field services apart. This is not the account the amount of destruction, but if there is destruction. The naves are going and returning, with the destruction prices collected and with everything except</p>
<p>Another method of making fleet easily, is to make the Moon fleetsave Moon, in which enemies can't make phalanx the moons (Because these is that have the sensor!)</p>
BODY;
$LNG['questions'][2][3]['title']	= 'Moons';
$LNG['questions'][2][3]['body']		= <<<BODY
<p>A moon can form when a field of debris has at least some 100,000 units, which is then a 1% chance opportunity moon. Maxsimum is only 20% chance no matter how big the debris field is.</p>
<h3>General</h3>
<p>The moons may have names like Planets but normally the default name is "Moon". You can have more than one moon, but only one per planet. The Satan © lites have the advantage that one of them invisible for the Fleetsave. On the Moon, you can build Warehouses, tank of DeutÃ © River, Fabrica de Robots or Nanites, Moonbase, Sensor Phalanx and the Portal Leap Quantico</p>
<h3>Sizes of moons</h3>
<p>The moon can be created depending on the number of destroyed units in a battle.The greatest chance of creating a simple moon is by destroying 1667 Light Cargos/Fighters that creates a chance of 20% for the moon. Light Cargos are recommended because they are easy to destroy.</p><p>The targeted planet should have defenses on the planet sufficient to destroy those ships. It is recommended to build at least 3334 Missle Launchers or Light Laser Turrets.</p><p>The huge amounts that will be made of Destruction, will determine the size of moon around your planet</p><p>Probability for Moons between 1% and 19% is of random size and probability of 20% the moon will have 8000 MILES in diameter<br>Regular moons are never exceeding 8944 km in diameter.</p>
<h3>Construction</h3>
<p>The buildings can be Warehouses, tank of Deuterium, manufactures of Robots or Nanites, Hangar, deposit of Alliance, Moonbase, Sensor Phalanx and the Jumpgate. The Hangar is useless on the moon because you can transfer your ships from the planet. The deposit of Alliance will be useful for defending the Moon attacks<br>The three specific buildings on the moon are:</p>
<ul><li><p><b>Lunar Base</b><br>It is used to create new fields, in which are added 3 new fields for each level</p></li>
<li><p><b>Sensor Phalanx</b><br>It is used to see the activities of the fleet to the enemy planet, but this can not view of the moons. Has a limited range of galaxies, which are augmented by nivel</p></li>
<li><p><b>Jumpgate How romantic</b><br>This is used for transferring fleet from one moon to another instantaneously. This can NOT be used to transfer resources.</p></li></ul>
<p>Here is a list of the ideal development of a Moon:<br>
<b>Legend:</b><br>
MB – Moon Base<br>
SP – Phalanx<br>
ST – Jumpgate<br>
RB – Robots Factory</p>
<p>MB1 – RB1 – RB2 – MB2 – SP1 – RB3 – MB3 – SP2 – RB4 – MB4 – SP3 – RB5 – MB5 – SP4 – RB6 – MB6 – SP5 – SP6 – MB7 – SP7 – SP8 – MB8 – ST1<br>
This order is only suggested if you are newbie, because of course the more experienced players have their idea of development<p>
<h3>Destruction of Moon</h3>
<p>The moon can also be destroyed again, which is only allowed with specific ships.</p>
<p>In the Fleet menu, select the ships called "Battle Fortress". When you arrive at the moment of choosing the mission to the Moon, choose "Destroy". These missions are not always successful! The bigger the moon is, more Battle Fortresses will be required and it becomes riskier to attempt the destruction of the moon!</p>
<h3>Size of the Moon:</h3>
<p>Destruction of 100000 units can render a 1% probability. The maximum probability is 20%.<p>
BODY;
$LNG['questions'][2][4]['title']	= 'Alliance';
$LNG['questions'][2][4]['body']		= <<<BODY
<h3>How do I form an Alliance</h3>
<p>Go to the menu "Alliance" and select "Create Alliance". In this page the TAG (Acronym) of the Alliance and the name of this. After these steps, run a fundaste Alliance</p>
<p>Below you will find the following links:<br>"Members": Here you can see the list of all members<br>"Your rank": Here encontarÃ to your "patent" or rank of the Alliance if this is s administrator, next will find the menu Administration<br>"Global Message": This function you can send a general message to s all the existing players in the Alliance</p>
<h3>Management of Alliance</h3>
<p>In this menu you can s edit the description of the Alliance, if you wish to delete, if you want to edit the "patents" or ranks, the pacts and still edit the members<br>The external text is a brief description of your Alliance for all members who visit the page of the Alliance, as also the inner text serves to exclusive content only of the members of the Alliance, as enemy, allied coordenadadas, coordinates, etc.<br>Also in the settings, you can edit the image that's displayed from the Alliance and also you can s specify the text of the application. you can also change the name of the position of administrator, that is typically "Leader" or "founder"<br>"Dissolve Alliance" is the function that makes clear the Alliance. If you want to abandon the Alliance but do you want to delete, then do Give/Accept Alliance</p>
BODY;
