<?php

$LNG['faq']			= array(
"<font size=3>Buildings</font>" => "The first thing you should focus on in DarkoGame is your resource generating buildings. These are the Metal Mine, Crystal Mine, and Deuterium Synthesizer. They will provide all of the resources you need to build your empire and thus upgrading them as high as possible as quickly as possible should be your number one priority in the game. Each of these buildings requires energy to operate, and if your energy output becomes less than the intake of these three structures, they will not perform up to par. Before you upgrade a building, you can always click the image of the building itself and see how much more energy the next level will require. Again, it is extremely vital that you upgrade these structures as quickly as possible. They are directly proportionate to how quickly you can advance in the game. ",
"" => "The second priority in the building section for a new emperor are buildings that do not require energy to operate. That is to say, they do not take away from any surplus energy that you may have. These are the Robotics Factory, Shipyard, and Research Lab. New buildings options will appear once you have reached the requirements to create them. For example, it is a requirement to have a level 2 Robotics Factory before you can build a shipyard. The higher the level of the Robotics Factory the quicker you can upgrade your buildings and build ships. The level of the shipyard itself partially determines what ships or defenses you can create. The second determination in what ships or defenses you can create is if you have researched the appropriate level of technology for each in the research lab. This leads us to the next section, technology.",
"<font size=3>Technology</font>" => "The Technology button on the left menu will tell you all the requirements for researching any technology and creating any building, ship, or defense that the game has to offer. It also details what is needed in order to recruit any officers. You can easily get an idea of what you have and what is still needed by the green/red color codes. Likewise, you can click on the name of any of the items to read a detailed description of the item and what it is and does. Use this often as it will be a good map for you to accomplish the goals you want to obtain in game in the order you wish to obtain them. When you are researching a new technology, all of the research labs on all of your planets are in use, and they cannot be upgraded while they are in use.",
"<font size=3>Galaxy</font>" => "This option in your main menu is a way to view a map of sorts of what is around you in the cosmos. It does cost a small amount of deuterium to view the map, and each planet is given a certain address of sorts in the map view. The addresses are laid out in a X:Y:Z format, where X = the individual galaxy, Y = the solar system, and Z = the orbital slot in relation to the star. The orbital slots are 1-15 where slot one is closest to the star, slot 15 is the furthest away (this is good to know when building solar satellites as the closer they are to the sun, the greater their output of energy is.) There is also a 16th slot reserved specifically for what we will discuss in the next section, dark matter and expeditions.",
"<font size=3>Dark Matter</font>" => "Dark matter is obtained through expeditions into the vastness space where your fleet may happen to recover it, or through donations. It is used to recruit officers. Astrophysics must first be researched in the lab, and there is indeed a good deal of risk involved with sending ships on them. Likewise, there are other possible rewards aside from the dark matter itself. For instance, you may encounter aliens, pirates, or even black holes and loose some or all of your ships. You may encounter abandoned ships and return home with a more substantial fleet than you ventured out with. Also, the potential rewards are proportionately increased with the size of the fleet that you send out, as well as with the scale of ships you send. Expeditions are a wise way to get ahead in the game, mainly due to the fact that officers are terribly valuable.",
"<font size=3>Officers</font>" => "These guys really increase your opportunities and help you grow quickly in the game. I cannot stress enough the fact that you should be sending out expeditions all the time nonstop until you have indeed maxed out every one. Any losses incurred in doing so will be more than compensated for once you have. They can do things such as double the amount of resources a mine gathers per hour to grant you the ability to create the most powerful ship in the game. On the technology page, you can click each officer and see what their individual benefits are as well as which ones you need to recruit in order to unlock others. ",
"<font size=3>Resources</font>" => "The resources screen will show you your output of each of the resources per hour/day/week as well as your energy output. This is where you can dial down the production percentage of mines if you exceed your total energy which may be needed from time to time. ",
"<font size=3>Merchant</font>" => "The merchant is indeed invaluable. Here you can exchange one resource for another between Metal, Crystal, and Deuterium. The exchange rate between Metal, Crystal, and Deuterium is 4/2/1, which means that you will get twice the amount of Crystal as the Deuterium you give, and twice the amount of Metal as Crystal you give. For example: 4000 Metal = 2000 Crystal = 1000 Deuterium, and they can be exchanged amongst themselves however you see fit.",
"<font size=3>Defenses/Shipyard</font>" => "I grouped these two screen together because they are quite similar as you will see in game. They both require the shipyard and will use the same queue for building. Defense is where you build your planetary defenses. Clicking on the image of any given defense option will tell you its statistics such as how many hit points it has, its attack strength, shield strength, etc... A planet that is not defended is a planet that is begging for someone to come and take its resources, however - at first you should be spending your resources on building upgrades as fast as they come in and therefore this is not an immediate priority. The shipyard is similar in that clicking the image of each ship will tell you its individual statistics, and likewise, creating a fleet is not the first priority a new emperor needs concern themselves with. A weak planet with a large amount of ships in orbit is a signpost to another player that they can come destroy the ships and steal the resources quite easily with a greater number of ships. ",
"<font size=3>Battle</font>"	=> "Here is where the real fun begins. In order to succeed on the battlefield, one must have grasped most of the basics of the overall game, and I will not go into every detail, just the basics of how battle works. In any given fight, any ships that get destroyed have a chance to leave some of their resources used for creating them floating around the planet in what is called a debris field. These fields can be harvested and the resources taken back to your planet and used to further your own empire. If the battle is large enough, and enough debris is created, a moon might form around the planet AT THE SAME TIME the debris field itself is formed. At most there is a 20% chance to form a moon. However, I digress - back to the battle... Make sure before you launch any attack that you have spied your target and are sending enough ships to come out victorious, unless you just plan on loosing all the ships you send. Likewise have enough recyclers handy to get out there and harvest any debris field before someone else gets to it first.",
"" => "There are three possible outcomes to any battle: win, loose, or draw. If the attacker wins, they will take as much of the resources on the planet at that time as their ships cargo holds can hold and return to their point of origin with it. If the attacker looses, then all of their ships will be destroyed and nothing returns. If it is a draw, the surviving ships will return to their point of origin, but they will not loot any resources from the planet they attacked. For the defending planet, any defenses that are destroyed during the attack will have a chance to immediately reappear after the battle is concluded. Therefore, your planet may be attacked, you may loose and get looted, but still end up with a portion of your defenses left.",
"<font size=3>Colonization</font>" => "This last section will be somewhat of a matter of opinion and debatable to some. I personally feel that the quickest way to grow in this game is to colonize as many planets as you can as fast as you possibly can. Keeping in mind that the initial focus for any new colony is to build and upgrade resource generating buildings as quickly as possible. I also recommend that these planets be spread as far as possible throughout the open universe. There 9 Galaxies, Each galaxy contains 499 solar systems. Each system has 15 Potential planets to colonize. There are some issues with spreading so far in that it takes a lot of time and fuel to transport resources amongst the planets, but I feel that it opens more opportunities later on in the game for things such as quickly hitting any given target or getting to any debris field before someone else. ",
"" => "In order to colonize a new planet, start by going to your fleet screen. In the open field next to colony ship, place a 1 and click continue. On the following page, input the destination address for the galaxy, solar system and slot you want to send your colony ship to create a new colony in the X:Y:Z format and click continue. Bare in mind that there is sometimes a sweet-spot for planets with a greater number of fields in slots 4-6, but not always. Now your happy little colonial explorers are on their way to expand your ever-growing empire!.",
"<font size=2>You have more questions? Send a PM with your question via Support Ticket.</font>" => "",
);

$LNG['faq_overview']	= "Beginners Guide";
?>