<?php

$LNG['faq']                        = array(
"<font size=3>Quelles mati&egrave;res premi&egrave;res sont-ils?</font>" => "Les principales mati&egrave;res premi&egrave;res sont en m&eacute;tal, en cristal et le deut&eacute;rium. Ces mesures sont n&eacute;cessaires pour les b&acirc;timents, la recherche, l'ing&eacute;nierie de la construction navale et la fabrication des locaux de la d&eacute;fense nationale. L'&eacute;nergie permet &agrave; vos mati&egrave;res premi&egrave;res de travail fonctionne sur 100%. Si vous devez produire moins d'&eacute;nergie que vous aviez besoin, votre travail de production des mati&egrave;res premi&egrave;res est r&eacute;duite.<br>",
"<font size=3>Quel est le nombre en vert sous les mati&egrave;res premi&egrave;res?</font>" => "Ce nombre indique la taille de votre stocke de ressources. Si les hangars sont pleins, vos mines ne produisent plus de mati&egrave;res premi&egrave;res.<br>",
"<font size=3>Qu'est-ce que la mati&egrave;re sombre et qu'est-ce que j'en est besoin ?</font>" => "La mati&egrave;re noire est une mati&egrave;re premi&egrave;re qui n'est pas produit par une &oelig;uvre. Avec cette mati&egrave;re premi&egrave;re, vous pouvez en laboratoire et le personnel vous obtenir un couple de petits boni dans la cat&eacute;gorie, dans laquelle le boni du personnel ne vont jamais au large. Le boni de laboratoire ce qui concerne respectivement 24 h. <br> En outre vous avez besoin de mati&egrave;re noire pour le march&eacute;. . Vous pouvez pour 750 une sombre et la mati&egrave;re y faire, avec un distributeur de mat&eacute;riaux bruts (m&eacute;tal, cristal, deut&eacute;rium) swap <br> Vous pouvez la mati&egrave;re noire de 2 fa&ccedil;ons diff&eacute;rentes obtenir: <br> 1 Dans la galaxie, vous devez aller &agrave; la position 16 plan&egrave;te juste en dessous et une flotte &agrave; l'&eacute;l&eacute;gance, ce qui peut revenir avec une mati&egrave;re noire, mais aussi &ecirc;tre d&eacute;truits. <br> 2 Si vous avez une lune et le navire de intergalactique collectionneurs affaire D., vous devez envoyer le navire &agrave; votre seule lune &agrave; l'examen. Cependant, le navire lui-m&ecirc;me d&eacute;truit apr&egrave;s la mission par lui-m&ecirc;me. Elle est d&eacute;sactiver, pour une meilleur &eacute;galit&eacute; du jeu",
"<font size=3>Comment puis-je lancer plusieurs construction ?</font>" => "Vous pouvez cr&eacute;er / &eacute;tendre vos travaux et aussi d'autres b&acirc;timents dans le cadre du renforcement de vos mines. <br> Vous pouvez emballer un maximum de 5 b&acirc;timents en arch&egrave;terie. <br> Si vous, cependant, ne devrait pas disposer de ressources suffisantes pour les b&acirc;timents suivants dans la fabrication d'archets, l'archet est rompu.",
"<font size=3>Quel effet a de d&eacute;vellopp&eacute; des b&acirc;timents?</font>" => "Chaque plan&egrave;te a seulement un certain nombre de pays cultivables. Chaque b&acirc;timent et chaque &eacute;tape de construction besoin de 1 <br> pays libre avec des recherches et des b&acirc;timents am&eacute;lior&eacute;s (pour la centrale nucl&eacute;aire par exemple) votre production peut &ecirc;tre augment&eacute;e et que vous pouvez faire un, ou plusieurs, vous tirez vers le bas des b&acirc;timents. <br> Rompre dure pendant un certain temps en fonction de b&acirc;timent / niveau, en plus, vous obtenez un couple de mati&egrave;res premi&egrave;res en arri&egrave;re.",
"<font size=3>O&ugrave; puis-je voir combien, de mati&egrave;res premi&egrave;res produire mes mines?</font>" => "Vous voyez dans le menu de gauche sous la production point combien la production totale des mati&egrave;res premi&egrave;res unique que vous avez. <br> En outre, vous pouvez ajuster, avec combien vos mines doit travailler. Moins ils travaillent, plus la consommation d'&eacute;nergie de chacune des mines est basse. ",
"<font size=3>Quelle est la fonction du simulateur d'attaque?</font>" => "Ceci a &eacute;t&eacute; d&eacute;velopp&eacute; pour faire un petit aper&ccedil;u du syst&egrave;me de lutte possible pour vous. En outre, vous pouvez aussi tester comme un combat pourrait finir environ.",
"<font size=3>Ce qui me s'attend au menu: Galaxie?</font>" => "La galaxie vous montre le point de vue de la v&ocirc;tre / vos plan&egrave;tes et que l'un de vos co&eacute;quipiers. Vous pouvez diriger de nombreuses actions de l'attaque jusqu'&agrave; la destruction d'ici. <br> Vous pouvez passer Galaxies et le syst&egrave;me d'avant en arri&egrave;re mais la prudence entre le seul par clic vous utilisez une hausse de 10 deut&eacute;rium. <br> Pour ex&eacute;cuter une action, vous devez cliquer une seule &agrave; la position d&eacute;sir&eacute;e (1-16). Apr&egrave;s que vous voyez un sondage aupr&egrave;s de vos objectifs &agrave; court terme, la flotte disponible. <br> Pour le transport par exemple s&eacute;lectionne vos navires, pour votre action missionnaire, rectifier le tir et la vitesse, passe une commande ((seulement possible avec au moins un v&eacute;hicule marchandises de la flotte)), et commence la mission. Vous pouvez alors voir dans la flotte &eacute;l&eacute;ment de menu qui vous flottes, quelles actions mener et quand ils sont termin&eacute;s.",
"<font size=3>Tout le monde m'attaque, comment puis-je me prot&eacute;ger? </font>"=> "Le plus important est: Vous n'obtenez pas de panique. Qui est tr&eacute;pidante fait habituellement des erreurs. <br> Jetez un oeil, &agrave; laquelle la plan&egrave;te flotte adverse est absente et combien de temps ces besoins encore <br> Vous avez les possibilit&eacute;s suivantes:. vos mati&egrave;res premi&egrave;res et de la flotte s&eacute;curis&eacute;, vous avez mis pour la lutte, ou en utilisant votre mati&egrave;res premi&egrave;res . plus ou moins insens&eacute;e <br> <b> sauvegarde des mati&egrave;res premi&egrave;res et de la flotte: </ b> <br> Si vous avez un ou plusieurs v&eacute;hicules de marchandises, vous cliquez sur la galaxie et de choisir une plan&egrave;te occup&eacute;e dans votre proximit&eacute; <. br> S&eacute;lectionnez vos navires et des ressources, &agrave; obtenir le transport de commande et envoyez votre flotte l&agrave;-bas. Il suffit de casser l'ordre de votre flotte, si l'attaque doit &ecirc;tre pass&eacute;, la flotte de menu. <br> Vous pouvez aussi tout de m&ecirc;me garantir votre bateaux si vous &ecirc;tes absent pendant un certain temps. L'important est que vous ne remplir les navires, les v&eacute;hicules utilitaires avec 1 des mati&egrave;res premi&egrave;res lorsque vous prot&eacute;ger. <br> Il vole votre flotte de la plan&egrave;te, d&eacute;chargements de cette mati&egrave;re premi&egrave;re et retourne &agrave; nouveau sans pertes. Il est encore plus large Enregistrer prend, cela devient aper&ccedil;u suppl&eacute;mentaire professedly dans un bient&ocirc;t.",
"<font size=3>Comment avoir plusieurs plan&egrave;tes ?</font>" => "Il vous faut la technoligie ASTOPHISIQUE de d&eacute;vellopp&eacute;. Ensuite construire un vaisseau de colonisation. Et enfin choisir un plan&egrave;te dans tout l'univers qui n'est pas d&eacute;j&agrave; occup&eacute; par d'autres joueurs !",
"<font size=3>Les Diff&eacute;rentes plan&egrave;tes</font>" => "Les plan&egrave;tes vont de 1 &agrave; 15 dans un systeme solaire. La plan&egrave;te 1 &eacute;tant la plus proche du soleil, produit plus d'&eacute;nergie avec la central et les satelites solaire que n'importe quels plan&egrave;tes. La plan&egrave;tes 15 &eacute;tant la plus loin produit plus de deut&eacute;rium que n'importe quels plan&egrave;tes. Et pour finir, les plan&egrave;tes 4,5,6 sont celles qui on le plus de places! A vous de faire le bon choix maintenant.",
"<font size=3>Qu'est-ce que la protection de Noob signifie et comment cela fonctionne?</font>" => "La protection Noob a &eacute;t&eacute; import&eacute; de donner de nouveaux joueurs la chance d'apprendre le jeu sans &ecirc;tre abus&eacute; par tous les acteurs comme une ferme &agrave; la fois. Par la protection Noob on doit simuler et d'apprendre la chance, sans &ecirc;tre en mesure de faire beaucoup de mal. Il faut utiliser cette chance d'apprendre Enregistre par exemple <br> caract&eacute;ristiques <br> Insolite <b>: </ b> La protection <br> Noob est avec les joueurs, qui est inactif d&eacute;sactive. La protection Noob va aux points principe &agrave; 5.000. M&ecirc;me si l'on est dans la protection Noob, on peut &ecirc;tre attaqu&eacute;. Ces environ sont bien aussi forte que de joueurs. Tous les joueurs de ces moins de 20% des points de son propre ont, sont pour un d&eacute;butant dans la protection et vous ne pouvez pas attaquer. Tous les joueurs de plus de 500% des points de ses propres ont sont repr&eacute;sent&eacute;s sous forme solide, car on se trouve &ecirc;tre dans la protection de ces Noob et ne peut pas &ecirc;tre attaqu&eacute;. Tous ces joueurs une entre 20% et 500% des points de son propre a, peut donc attaquer et &ecirc;tre attaqu&eacute; par ces derniers.",
"<font size=3>Le mode vacances comment fonctionne t-il?</font>" => "Le mode de vacances Holthe a &eacute;t&eacute;, autour de mises en &eacute;tant heureux d'&ecirc;tre pour vous aussi le temps d'une minute pacifique. Vous devez par exemple partir en vacances et vous pouvez / ne veulent pas se connecter dans le jeu il ya, peut profiter du mode de vacances. Vous &ecirc;tes prot&eacute;g&eacute; dans ce domaine, ne peut donc pas &ecirc;tre attaqu&eacute;. Votre mines produisent &eacute;galement rien en ce moment, si. Le mode de vacances va au moins 48 h, vous pouvez le d&eacute;sactiver dans les attitudes, simple &agrave; au moins 48 h &agrave; nouveau.",
"<font size=3>Quand mon compte est supprim&eacute;?</font>" => "Votre compte est automatiquement supprim&eacute; si vous n'&ecirc;tes pas connect&eacute; pendant 30 jours. Vous pouvez le supprimer manuellement aussi, il suffit d'aller dans les attitudes et supprimer votre compte juste en dessous. Apr&egrave;s 7 jours sur votre compte puis dispara&icirc;t du serveur. Votre nom est un petit bout de 7 jours sans vous connecter <b> i </b>. Apr&egrave;s 28 jours vous obtenez un grand <b> I </b>. Vous avez la possibilit&eacute; de laisser votre compte supprimer attitudes dans le menu d'ailleurs. &agrave; l'activation de l'option de l'heure exacte de la suppression vous permet de vous montr&eacute;.",
"<font size=3>J'ai un probl&egrave;me je vais faire quoi?</font>" => "Il est le billet d'appui dans l'&eacute;l&eacute;ment de menu, c'est &agrave; votre disposition &agrave; probl&egrave;mes, les insultes, etc et il est r&eacute;pondu par notre &eacute;quipe utile &agrave; l'agr&eacute;able. <br> En cas de questions sur le jeu, vous devriez plut&ocirc;t utiliser le chat et / ou le forum, si. <br> En r&egrave;gle g&eacute;n&eacute;rale, des tickets de support sera r&eacute;pondu au plus tard &agrave; 24 h. Vous recevez un message avec indication de l'appel du ticket de support.",
"<font size=2><br>Encore des questions? Alors envoyez-nous un ticket de support!</font>" => "<br><br>",

);

$LNG['faq_overview']        = "FAQ";

// Traduction français by HaloRaptor . All rights reversed (C) 2011 haloraptor33@gmail.com

?>