<?php

$LNG['faq']			= array(
"<font size=3>Edificios</font>" => "Lo primero que debe enfocarse en sus edificios es en generar de recursos. Estas son las minas de metal, minas de cristal, y Sintetizador de deuterio. Ellos le proporcionar&aacute;n todos los recursos que necesita para construir su imperio y lo que les mejora lo m&aacute;s alto posible lo m&aacute;s r&aacute;pidamente posible debe ser su prioridad n&uacute;mero uno en el juego. Cada uno de estos edificios requiere energ&iacute;a para funcionar, y si su producci&oacute;n de energ&iacute;a es inferior a la ingesta de estas tres estructuras, que no llevar&aacute; a cabo a la par. Antes de actualizar un edificio, siempre puedes hacer clic en la imagen del propio edificio y ver cu&aacute;nto m&aacute;s energ&iacute;a al siguiente nivel ser&aacute; necesario. Una vez m&aacute;s, es extremadamente importante que estas estructuras de actualizar lo m&aacute;s r&aacute;pidamente posible. Ellos son directamente proporcionales a la rapidez con que se puede avanzar en el juego. ",
"" => "La segunda prioridad en la secci&oacute;n de construcci&oacute;n de un nuevo emperador son edificios que no requieren energ&iacute;a para funcionar. Es decir, no toman lejos de cualquier exceso de energ&iacute;a que usted pueda tener. Se trata de la F&aacute;brica de Rob&oacute;tica, Astillero, y laboratorio de investigaci&oacute;n. Los nuevos edificios opciones aparecer&aacute;n una vez que han alcanzado los requisitos para su creaci&oacute;n. Por ejemplo, es un requisito de disponer de un nivel 2 de f&aacute;brica rob&oacute;tica antes de poder construir un astillero. Cuanto mayor sea el nivel de la f&aacute;brica de Rob&oacute;tica Cuanto más r&aacute;pido pueda mejorar tus instalaciones y construir sus naves. El nivel del propio astillero determina parcialmente lo que los buques o las defensas que puede crear. La segunda determinaci&oacute;n en lo que los buques o las defensas que puede crear es si usted ha investigado el nivel apropiado de la tecnolog&iacute;a para cada uno en el laboratorio de investigació&oacute;n. Esto nos lleva a la siguiente secció&oacute;n, la tecnologí&iacute;a.",
"<font size=3>Tecnologia</font>" => "El bot&oacute;n de la tecnolog&iacute;a en el men&uacute; de la izquierda le dir&aacute; todos los requisitos para la investigaci&oacute;n de cualquier, tecnolog&iacute;a y la creaci&oacute;n de cualquier edificio, barco, o de la defensa que el juego tiene para ofrecer. Tambi&eacute;n detalla lo que se necesita para contratar a cualquier funcionario. Usted puede tener una idea de lo que tienes y lo que a&uacute;n es necesario por el verde / c&oacute;digos de color rojo. Del mismo modo, puede hacer clic en el nombre de cualquiera de los art&iacute;culos para leer una descripci&oacute;n detallada de los puntos y no lo que es y. Use esto con frecuencia ya que ser&aacute; un buen mapa para que usted pueda lograr las metas que desea obtener en el juego en el orden que deseen obtenerlos. Cuando se está investigando una nueva tecnolog&iacute;a, todos los laboratorios de investigaci&oacute;n en todos sus planetas est&aacute;n en uso, y no se pueden actualizar mientras est&aacute;n en uso.",
"<font size=3>Galaxia</font>" => "Esta opci&oacute;n en su men&uacute; principal es una forma de ver un mapa de clase de lo que te rodea en el cosmos. Cu&aacute;nto cuesta una peque&ntilde;a cantidad de deuterio para ver el mapa, y cada planeta se le da una cierta direcci&oacute;n de la clase en la vista de mapa. Las direcciones se establecen en un X: Y: Z formato, donde X = la galaxia individual, Y = el sistema solar, y Z = la posici&oacute;n orbital en relaci&oacute;n con la estrella. Las ranuras orbitales son 1-15, donde una ranura más cercana a la estrella, ranura 15 es el m&aacute;s alejado (esto es bueno saber la hora de construir sat&eacute;lites solares, cuanto m&aacute;s cerca est&aacute;n al sol, mayor es su producci&oacute;n de energ&iacute;a.) Hay tambi&eacute;n una ranura 16a reservados espec&iacute;ficamente para lo que vamos a discutir en la pr&oacute;xima secci&oacute;n, la materia oscura y expediciones.",
"<font size=3>Materia Oscura</font>" => "La materia oscura se obtiene a trav&eacute;s de expediciones en el espacio donde su inmensidad de la flota puede suceder a su recuperaci&oacute;n, oa trav&eacute;s de donaciones. Se utiliza para reclutar a oficiales. Astrof&iacute;sica primero debe ser investigado en el laboratorio, y en efecto, hay una buena cantidad de riesgo implicado con el env&iacute;o de buques por ellos. Asimismo, existen otros posibles recompensas, aparte de la materia oscura en s&iacute; misma. Por ejemplo, puede encontrar los extranjeros, los piratas, o incluso los agujeros negro y suelta todas o algunas de sus naves. Es posible que encuentre abandonado los barcos y regresar a casa con una flota m&aacute;s importante de lo que se aventur&oacute; hacia fuera con. Adem&aacute;s, las recompensas potenciales son incrementará proporcionalmente con el tama&ntilde;o de la flota que usted env&iacute;a, as&iacute; como con la escala de los buques que env&iacute;e. Expediciones son una forma inteligente de salir adelante en el juego, debido principalmente al hecho de que los funcionarios son terriblemente valiosos.",
"<font size=3>Oficiales</font>" => "Estos tipos realmente aumentar sus oportunidades y le ayudar&aacute; a crecer r&aacute;pidamente en el juego. No puedo hacer suficiente hincapi&eacute; en el hecho de que usted deber&iacute;a ser el env&iacute;o de expediciones todo el tiempo sin parar hasta que haya hecho llegado al m&aacute;ximo de cada uno. Cualquier p&eacute;rdidas sufridas en hacerlo, ser&aacute; m&aacute;s que compensada por una vez que usted tiene. Ellos pueden hacer cosas como el doble de la cantidad de recursos que re&uacute;ne a una mina por hora que le conceda la posibilidad de crear la nave m&aacute;s poderosa en el juego. En la p&aacute;gina de la tecnolog&iacute;a, puede hacer clic en cada oficial y ver lo que sus beneficios son individuales, as&iacute; como que los que necesita para contratar con el fin de desbloquear los dem&aacute;s. ",
"<font size=3>Recursos</font>" => "La pantalla le mostrar&aacute; los recursos de su salida de cada uno de los recursos por hora / d&iacute;a / semana, as&iacute; como la producci&oacute;n de energ&iacute;a. Aqu&iacute; es donde usted puede marcar hasta el porcentaje de producci&oacute;n de las minas si se excede el total de energ&iacute;a que puede ser necesario de vez en cuando. ",
"<font size=3>Mercader</font>" => "El comerciante es de hecho un valor incalculable. Aqu&iacute; usted puede cambiar un recurso por otro entre Metal, Cristal y Deuterio. El tipo de cambio entre el metal, cristal y deuterio es 4/2/1, lo que significa que usted obtendr&aacute; el doble de la cantidad de cristal como el deuterio te dan, y el doble de la cantidad de metal como de cristal que dan. Por ejemplo: = 2000 4000 Metal Cristal Deuterio = 1000, y se pueden intercambiar entre s&iacute;, a tu forma.",
"<font size=3>Defensas</font>" => "He agrupado estas dos pantallas juntos porque son muy similares como se ver&aacute; en el juego. Ambos requieren el astillero y utilizar&aacute; la misma cola para la construcci&oacute;n. Defensa es el lugar donde construir sus defensas planetarias. Al hacer clic en la imagen de cualquier opci&oacute;n de defensa que figura le dir&aacute;n sus estad&iacute;sticas, como cu&aacute;ntos puntos tiene &eacute;xito, su fuerza de ataque, la fuerza de paneles, etc .. Un planeta que no se defiende es un planeta que est&aacute; pidiendo que alguien venga y sus recursos, sin embargo - en un principio que deber&iacute;a invertir sus recursos en la construcci&oacute;n de las actualizaciones tan r&aacute;pido como llegan y por lo tanto esta no es una prioridad inmediata. El astillero es similar en que al hacer clic en la imagen de cada barco le dicen sus estad&iacute;sticas individuales, y adem&aacute;s, la creaci&oacute;n de una flota no es la primera prioridad un nuevo emperador ocuparse de las necesidades. Un planeta d&eacute;bil con una gran cantidad de naves en ó&oacute;rbita es una señ&ntilde;al a otro jugador que puede venir a
 destru&iacute;r las naves y robar los recursos con toda facilidad con un mayor n&uacute;mero de buques. ",
"<font size=3>Batallas</font>"	=> "Aqu&iacute; es donde la verdadera diversi&oacute;n comienza. Para tener &eacute;xito en el campo de batalla, uno debe haber captado la mayor parte de los fundamentos del juego en general, y yo no voy a entrar en cada detalle, s&oacute;lo lo b&aacute;sico de las obras batalla c&oacute;mo. En cualquier lucha, ante cualquier proceso que se destruyen los buques tienen la oportunidad de dejar algunas de sus recursos utilizados para la creaci&oacute;n flotando alrededor del planeta en lo que se llama un campo de escombros. Estos campos pueden ser cosechadas y los recursos sean devueltos a su planeta y utilicen para su propio imperio. Si la batalla es suficientemente grande, y los escombros se crea lo suficiente, podr&iacute;an formar una luna alrededor del planeta AL MISMO TIEMPO el campo de escombros en s&iacute; est&aacute; formado. A lo sumo hay una probabilidad de 20% para formar una luna. Sin embargo, estoy divagando - volver a la batalla ... Aseg&uacute;rese de que antes de lanzar cualquier ataque que te han espiado a tu objetivo y el enví&iacute;o de buques pueda volver a salir victoriosos, a menos que usted acaba de perder el plan de todas
 las naves qu&iacute;en env&iacute;e.
Del mismo modo se han recicl&aacute;do a mano lo suficiente como para salir y cosechar cualquier campo de los restos antes de que alguien m&aacute;s tiene la oportunidad por primera vez.",
"" => "Hay tres posibles resultados de cualquier batalla: ganar, perder o dibujar. Si el atacante gana, sino que tendr&aacute; la mayor cantidad de recursos en el planeta en ese tiempo ya medida que los buques de carga tiene puede almacenar y volver a su punto de origen de la misma. Si el atacante pierde, entonces todas sus naves ser&aacute;n destruidas y no devuelve nada. Si hay empate, los barcos supervivientes vuelven a su punto de origen, pero no saquear los recursos del planeta, atacaron. Para defender el planeta, cualquier defensa que se destruyeron durante el ataque tendr&aacute; la oportunidad de volver a aparecer inmediatamente despu&eacute;s de la batalla ha concluido. Por lo tanto, su planeta puede ser atacado, se puede perder y saquearon conseguir, pero a&uacute;n as&iacute; terminar con una parte de sus defensas izquierda.",
"<font size=3>Colonizar</font>" => "Esta &uacute;ltima secci&oacute;n ser&aacute; algo de una cuesti&oacute;n de opini&oacute;n y discutible para algunos. Personalmente, creo que la forma m&aacute;s r&aacute;pida de crecer en este juego es para colonizar los planetas que puedas tan r&aacute;pido como le sea posible. Teniendo en cuenta que el foco inicial para cualquier nueva colonia es construir y mejorar los recursos de generaci&oacute;n edificios tan pronto como sea posible. Tambi&eacute;n recomiendo que estos planetas se extendi&oacute; tanto como sea posible en todo el universo abierto. Hay 9 galaxias, cada galaxia contiene 499 sistemas solares. Cada sistema tiene 15 planetas potencial para colonizar. Hay algunos problemas con la propagaci&oacute;n hasta la fecha en que se necesita una gran cantidad de tiempo y combustible para el transporte de los recursos entre los planetas, pero siento que se abre m&aacute;s oportunidades m&aacute;s adelante en el juego por las cosas lo m&aacute;s r&aacute;pidamente golpear ningú&uacute;n objetivo determinado o llegar a cualquier campo de escombros antes de otra persona.",
"" => "Con el fin de colonizar un nuevo planeta, empiece por visitar la pantalla de su flota. En el campo abierto junto a nave colonial, coloque un 1 y haga clic en continuar. En la p&aacute;gina siguiente, ingrese la direcci&oacute;n de destino de la galaxia, sistema solar y la ranura que desea enviar su nave colonial para crear una nueva colonia en la X: Y: Z formato y haga clic en continuar. Desnudo en cuenta que a veces hay un dulce de contado de los planetas con un mayor n&uacute;mero de campos en las ranuras 4-6, pero no siempre. Ahora su exploradores coloniales poco felices est&aacute;n en camino para expandir tu imperio cada vez mayor!.",
"<font size=2>Usted tiene m&aacute;s preguntas? Enviar un PM con su pregunta a trav&eacute;s de Ticket.</font>" => "",
);

$LNG['faq_overview']	= "Guia de Novatos";

// Traducido por ZideN
?>
