ALTER TABLE `prefix_config` DROP `stat_last_banner_update`,
 DROP `stat_banner_update_time`,
 DROP `ftp_server`,
 DROP `ftp_user_name`,
 DROP `ftp_user_pass`,
 DROP `ftp_root_path`,
 DROP `bgm_active`,
 DROP `bgm_file`;
ALTER TABLE `prefix_config` ADD `max_galaxy` TINYINT( 3 ) UNSIGNED NOT NULL DEFAULT '9',
 ADD `max_system` SMALLINT( 5 ) UNSIGNED NOT NULL DEFAULT '400',
 ADD `max_planets` TINYINT( 3 ) UNSIGNED NOT NULL DEFAULT '15',
 ADD `max_elements_build` TINYINT( 5 ) UNSIGNED NOT NULL DEFAULT '5',
 ADD `max_elements_tech` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT '2',
 ADD `max_elements_ships` TINYINT( 10 ) UNSIGNED NOT NULL DEFAULT '10',
 ADD `max_player_planets` TINYINT( 3 ) UNSIGNED NOT NULL DEFAULT '255',
 ADD `min_player_planets` TINYINT( 3 ) UNSIGNED NOT NULL DEFAULT '9',
 ADD `planet_factor`  FLOAT(2,1) NOT NULL DEFAULT '1.0',
 ADD `max_fleet_per_build` BIGINT(20) UNSIGNED NOT NULL DEFAULT '1000000',
 ADD `deuterium_cost_galaxy` INT(11) UNSIGNED NOT NULL DEFAULT '10',
 ADD `max_dm_missions` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
 ADD `max_overflow` FLOAT(2,1) NOT NULL DEFAULT '1.0',
 ADD `moon_factor` FLOAT(2,1) NOT NULL DEFAULT '1.0',
 ADD `moon_chance` TINYINT(3) UNSIGNED NOT NULL DEFAULT '20',
 ADD `darkmatter_cost_trader` INT(11) UNSIGNED NOT NULL DEFAULT '750',
 ADD `factor_university` TINYINT(3) UNSIGNED NOT NULL DEFAULT '8',
 ADD `max_fleets_per_acs` TINYINT(3) UNSIGNED NOT NULL DEFAULT '16',
 ADD `debris_moon` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
 ADD `vmode_min_time` INT(11) NOT NULL DEFAULT '259200',
 ADD `gate_wait_time` INT(11) NOT NULL DEFAULT '3600',
 ADD `metal_start` INT(11) UNSIGNED NOT NULL DEFAULT '500',
 ADD `crystal_start` INT(11) UNSIGNED NOT NULL DEFAULT '500',
 ADD `deuterium_start` INT(11) UNSIGNED NOT NULL DEFAULT '0',
 ADD `darkmatter_start` INT(11) UNSIGNED NOT NULL DEFAULT '0',
 ADD `ttf_file` VARCHAR(32) NOT NULL DEFAULT 'styles/arial.tff';
ALTER TABLE `prefix_config` CHANGE `uni` `uni` INT(11) NOT NULL AUTO_INCREMENT,
 CHANGE `VERSION` `VERSION` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
 CHANGE `users_amount` `users_amount` INT(11) UNSIGNED NOT NULL DEFAULT '1',
 CHANGE `game_speed` `game_speed` BIGINT(20) UNSIGNED NOT NULL DEFAULT '2500',
 CHANGE `fleet_speed` `fleet_speed` BIGINT(20) UNSIGNED NOT NULL DEFAULT '2500',
 CHANGE `resource_multiplier` `resource_multiplier` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '1',
 CHANGE `halt_speed` `halt_speed` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '1',
 CHANGE `Fleet_Cdr` `Fleet_Cdr` TINYINT(3) UNSIGNED NOT NULL DEFAULT '30',
 CHANGE `Defs_Cdr` `Defs_Cdr` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
 CHANGE `initial_fields` `initial_fields` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '163',
 CHANGE `uni_name` `uni_name` VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
 CHANGE `game_name` `game_name` VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
 CHANGE `game_disable` `game_disable` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
 CHANGE `close_reason` `close_reason` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
 CHANGE `metal_basic_income` `metal_basic_income` INT(11) NOT NULL DEFAULT '20',
 CHANGE `crystal_basic_income` `crystal_basic_income` INT(11) NOT NULL DEFAULT '10',
 CHANGE `deuterium_basic_income` `deuterium_basic_income` INT(11) NOT NULL DEFAULT '0',
 CHANGE `energy_basic_income` `energy_basic_income` INT(11) NOT NULL DEFAULT '0',
 CHANGE `LastSettedGalaxyPos` `LastSettedGalaxyPos` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
 CHANGE `LastSettedSystemPos` `LastSettedSystemPos` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '1',
 CHANGE `LastSettedPlanetPos` `LastSettedPlanetPos` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
 CHANGE `noobprotection` `noobprotection` INT(11) NOT NULL DEFAULT '0',
 CHANGE `noobprotectiontime` `noobprotectiontime` INT(11) NOT NULL DEFAULT '5000',
 CHANGE `noobprotectionmulti` `noobprotectionmulti` INT(11) NOT NULL DEFAULT '5',
 CHANGE `forum_url` `forum_url` VARCHAR(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'http://2moons.cc',
 CHANGE `adm_attack` `adm_attack` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
 CHANGE `debug` `debug` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
 CHANGE `lang` `lang` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
 CHANGE `stat` `stat` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
 CHANGE `stat_level` `stat_level` TINYINT(3) UNSIGNED NOT NULL DEFAULT '2',
 CHANGE `stat_last_update` `stat_last_update` INT(11) NOT NULL DEFAULT '0',
 CHANGE `stat_settings` `stat_settings` INT(11) UNSIGNED NOT NULL DEFAULT '1000',
 CHANGE `stat_update_time` `stat_update_time` TINYINT(3) UNSIGNED NOT NULL DEFAULT '25',
 CHANGE `stat_last_db_update` `stat_last_db_update` INT(11) NOT NULL DEFAULT '0',
 CHANGE `stats_fly_lock` `stats_fly_lock` INT(11) NOT NULL DEFAULT '0',
 CHANGE `cron_lock` `cron_lock` INT(11) NOT NULL DEFAULT '0',
 CHANGE `ts_modon` `ts_modon` TINYINT(1) NOT NULL DEFAULT '0',
 CHANGE `ts_server` `ts_server` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
 CHANGE `ts_tcpport` `ts_tcpport` SMALLINT(5) NOT NULL DEFAULT '0',
 CHANGE `ts_udpport` `ts_udpport` SMALLINT(5) NOT NULL DEFAULT '0',
 CHANGE `ts_timeout` `ts_timeout` TINYINT(1) NOT NULL DEFAULT '1',
 CHANGE `ts_version` `ts_version` TINYINT(1) NOT NULL DEFAULT '2',
 CHANGE `ts_cron_last` `ts_cron_last` INT(11) NOT NULL DEFAULT '0',
 CHANGE `ts_cron_interval` `ts_cron_interval` SMALLINT(5) NOT NULL DEFAULT '5',
 CHANGE `ts_login` `ts_login` VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
 CHANGE `ts_password` `ts_password` VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
 CHANGE `reg_closed` `reg_closed` TINYINT(1) NOT NULL DEFAULT '0',
 CHANGE `OverviewNewsFrame` `OverviewNewsFrame` TINYINT(1) NOT NULL DEFAULT '0',
 CHANGE `OverviewNewsText` `OverviewNewsText` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
 CHANGE `capaktiv` `capaktiv` TINYINT(1) NOT NULL DEFAULT '0',
 CHANGE `cappublic` `cappublic` VARCHAR(42) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
 CHANGE `capprivate` `capprivate` VARCHAR(42) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
 CHANGE `min_build_time` `min_build_time` TINYINT(2) NOT NULL DEFAULT '1',
 CHANGE `mail_active` `mail_active` TINYINT(1) NOT NULL DEFAULT '0',
 CHANGE `mail_use` `mail_use` TINYINT(1) NOT NULL DEFAULT '0',
 CHANGE `smtp_host` `smtp_host` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
 CHANGE `smtp_port` `smtp_port` SMALLINT(5) NOT NULL DEFAULT '0',
 CHANGE `smtp_user` `smtp_user` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
 CHANGE `smtp_pass` `smtp_pass` VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
 CHANGE `smtp_ssl` `smtp_ssl` ENUM('','ssl','tls') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
 CHANGE `smtp_sendmail` `smtp_sendmail` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
 CHANGE `smail_path` `smail_path` VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '/usr/sbin/sendmail',
 CHANGE `user_valid` `user_valid` TINYINT(1) NOT NULL DEFAULT '0',
 CHANGE `fb_on` `fb_on` TINYINT(1) NOT NULL DEFAULT '0',
 CHANGE `fb_apikey` `fb_apikey` VARCHAR(42) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
 CHANGE `fb_skey` `fb_skey` VARCHAR(42) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
 CHANGE `ga_active` `ga_active` VARCHAR(42) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0',
 CHANGE `ga_key` `ga_key` VARCHAR(42) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
 CHANGE `moduls` `moduls` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
 CHANGE `trade_allowed_ships` `trade_allowed_ships` VARCHAR(70) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '202,401',
 CHANGE `trade_charge` `trade_charge` VARCHAR(5) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '30',
 CHANGE `chat_closed` `chat_closed` TINYINT(1) NOT NULL DEFAULT '0',
 CHANGE `chat_allowchan` `chat_allowchan` TINYINT(1) NOT NULL DEFAULT '1',
 CHANGE `chat_allowmes` `chat_allowmes` TINYINT(1) NOT NULL DEFAULT '1',
 CHANGE `chat_allowdelmes` `chat_allowdelmes` TINYINT(1) NOT NULL DEFAULT '1',
 CHANGE `chat_logmessage` `chat_logmessage` TINYINT(1) NOT NULL DEFAULT '1',
 CHANGE `chat_nickchange` `chat_nickchange` TINYINT(1) NOT NULL DEFAULT '1',
 CHANGE `chat_botname` `chat_botname` VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '2Moons',
 CHANGE `chat_channelname` `chat_channelname` VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '2Moons',
 CHANGE `chat_socket_active` `chat_socket_active` TINYINT(1) NOT NULL DEFAULT '0',
 CHANGE `chat_socket_host` `chat_socket_host` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
 CHANGE `chat_socket_ip` `chat_socket_ip` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
 CHANGE `chat_socket_port` `chat_socket_port` SMALLINT(5) NOT NULL DEFAULT '0',
 CHANGE `chat_socket_chatid` `chat_socket_chatid` TINYINT(1) NOT NULL DEFAULT '1';