ALTER TABLE prefix_topkb CHANGE `id_owner1` `id_owner1` INT(11) UNSIGNED NOT NULL, CHANGE `id_owner2` `id_owner2` INT(11) UNSIGNED NOT NULL, CHANGE `gesamtunits` `gesamtunits` BIGINT(20) UNSIGNED NOT NULL, CHANGE `rid` `rid` VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `fleetresult` `fleetresult` ENUM('r', 'a', 'w') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE prefix_users_valid CHANGE `planet` `planet` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `ip` `ip` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `lang` `lang` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE prefix_users CHANGE `id_planet` `id_planet` INT(11) UNSIGNED NOT NULL DEFAULT '0', CHANGE `new_message` `new_message` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0', CHANGE `new_gmessage` `new_gmessage` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0', CHANGE `b_tech_planet` `b_tech_planet` INT(11) UNSIGNED NOT NULL DEFAULT '0', CHANGE `b_tech` `b_tech` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0', CHANGE `ally_id` `ally_id` INT(11) UNSIGNED NOT NULL DEFAULT '0', CHANGE `ally_rank_id` `ally_rank_id` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0', CHANGE `fb_id` `fb_id` BIGINT(15) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE prefix_supp CHANGE `ID` `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, CHANGE `player_id` `player_id` INT(11) UNSIGNED NOT NULL, CHANGE `subject` `subject` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `status` `status` TINYINT(1) UNSIGNED NOT NULL, CHANGE `universe` `universe` TINYINT(3) UNSIGNED NOT NULL;
ALTER TABLE prefix_statpoints CHANGE `id_owner` `id_owner` INT(11) UNSIGNED NOT NULL, CHANGE `id_ally` `id_ally` INT(11) UNSIGNED NOT NULL, CHANGE `stat_type` `stat_type` TINYINT(1) UNSIGNED NOT NULL, CHANGE `tech_rank` `tech_rank` INT(11) UNSIGNED NOT NULL, CHANGE `tech_old_rank` `tech_old_rank` INT(11) UNSIGNED NOT NULL, CHANGE `tech_count` `tech_count` INT(11) UNSIGNED NOT NULL, CHANGE `build_rank` `build_rank` INT(11) UNSIGNED NOT NULL, CHANGE `build_old_rank` `build_old_rank` INT(11) UNSIGNED NOT NULL, CHANGE `build_count` `build_count` INT(11) UNSIGNED NOT NULL, CHANGE `defs_rank` `defs_rank` INT(11) UNSIGNED NOT NULL, CHANGE `defs_old_rank` `defs_old_rank` INT(11) UNSIGNED NOT NULL, CHANGE `defs_count` `defs_count` INT(11) UNSIGNED NOT NULL, CHANGE `fleet_rank` `fleet_rank` INT(11) UNSIGNED NOT NULL, CHANGE `fleet_old_rank` `fleet_old_rank` INT(11) UNSIGNED NOT NULL, CHANGE `fleet_points` `fleet_points` BIGINT(20) UNSIGNED NOT NULL, CHANGE `fleet_count` `fleet_count` INT(11) UNSIGNED NOT NULL, CHANGE `total_rank` `total_rank` INT(11) UNSIGNED NOT NULL, CHANGE `total_old_rank` `total_old_rank` INT(11) UNSIGNED NOT NULL, CHANGE `total_count` `total_count` INT(11) UNSIGNED NOT NULL;
ALTER TABLE prefix_rw CHANGE `rid` `rid` VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `time` `time` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE prefix_planets CHANGE `id` `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, CHANGE `name` `name` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT 'Hauptplanet', CHANGE `id_owner` `id_owner` INT(11) UNSIGNED NULL, CHANGE `id_level` `id_level` TINYINT(1) UNSIGNED NULL DEFAULT '0', CHANGE `diameter` `diameter` INT(11) UNSIGNED NOT NULL DEFAULT '12800', CHANGE `field_current` `field_current` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0', CHANGE `field_max` `field_max` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '163', CHANGE `energy_used` `energy_used` INT(11) UNSIGNED NOT NULL DEFAULT '0', CHANGE `energy` `energy` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0', CHANGE `interceptor_misil` `interceptor_misil` INT(11) UNSIGNED NOT NULL DEFAULT '0', CHANGE `interplanetary_misil` `interplanetary_misil` INT(11) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE prefix_notes CHANGE `owner` `owner` INT(11) UNSIGNED NULL, CHANGE `universe` `universe` TINYINT(3) UNSIGNED NOT NULL;
ALTER TABLE prefix_messages CHANGE `message_owner` `message_owner` INT(11) UNSIGNED NOT NULL DEFAULT '0', CHANGE `message_sender` `message_sender` INT(11) UNSIGNED NOT NULL DEFAULT '0', CHANGE `message_type` `message_type` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0', CHANGE `message_from` `message_from` VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, CHANGE `message_subject` `message_subject` VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE prefix_fleets CHANGE `fleet_owner` `fleet_owner` INT(11) UNSIGNED NOT NULL DEFAULT '0', CHANGE `fleet_target_obj` `fleet_target_obj` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0', CHANGE `fleet_target_owner` `fleet_target_owner` INT(11) UNSIGNED NOT NULL DEFAULT '0', CHANGE `start_time` `start_time` INT(11) NULL;
ALTER TABLE prefix_diplo CHANGE `id` `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, CHANGE `owner_1` `owner_1` INT(11) UNSIGNED NOT NULL, CHANGE `owner_2` `owner_2` INT(11) UNSIGNED NOT NULL, CHANGE `level` `level` TINYINT(1) UNSIGNED NOT NULL, CHANGE `accept` `accept` TINYINT(1) UNSIGNED NOT NULL, CHANGE `universe` `universe` TINYINT(3) UNSIGNED NOT NULL;
ALTER TABLE prefix_config CHANGE `Fleet_Cdr` `Fleet_Cdr` TINYINT(3) UNSIGNED NOT NULL, CHANGE `Defs_Cdr` `Defs_Cdr` TINYINT(3) UNSIGNED NOT NULL, CHANGE `initial_fields` `initial_fields` INT(11) UNSIGNED NOT NULL, CHANGE `bgm_active` `bgm_active` TINYINT(1) UNSIGNED NOT NULL, CHANGE `game_disable` `game_disable` TINYINT(1) UNSIGNED NOT NULL, CHANGE `LastSettedGalaxyPos` `LastSettedGalaxyPos` TINYINT(3) UNSIGNED NOT NULL, CHANGE `LastSettedSystemPos` `LastSettedSystemPos` SMALLINT(5) UNSIGNED NOT NULL, CHANGE `LastSettedPlanetPos` `LastSettedPlanetPos` TINYINT(3) UNSIGNED NOT NULL, CHANGE `adm_attack` `adm_attack` TINYINT(1) UNSIGNED NOT NULL, CHANGE `debug` `debug` TINYINT(1) UNSIGNED NOT NULL, CHANGE `lang` `lang` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `ts_modon` `ts_modon` TINYINT(1) NOT NULL, CHANGE `ts_tcpport` `ts_tcpport` SMALLINT(5) NOT NULL, CHANGE `ts_udpport` `ts_udpport` SMALLINT(5) NOT NULL, CHANGE `ts_timeout` `ts_timeout` TINYINT(1) NOT NULL, CHANGE `ts_version` `ts_version` TINYINT(1) NOT NULL, CHANGE `ts_cron_interval` `ts_cron_interval` SMALLINT(5) NOT NULL, CHANGE `reg_closed` `reg_closed` TINYINT(1) NOT NULL, CHANGE `OverviewNewsFrame` `OverviewNewsFrame` TINYINT(1) NOT NULL, CHANGE `capaktiv` `capaktiv` TINYINT(1) NOT NULL, CHANGE `min_build_time` `min_build_time` TINYINT(2) NOT NULL, CHANGE `smtp_port` `smtp_port` SMALLINT(5) NOT NULL, CHANGE `user_valid` `user_valid` TINYINT(1) NOT NULL, CHANGE `fb_on` `fb_on` TINYINT(1) NOT NULL;
ALTER TABLE prefix_chat CHANGE `messageid` `messageid` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, CHANGE `user` `user` VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '', CHANGE `ally_id` `ally_id` INT(11) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE prefix_buddy CHANGE `sender` `sender` INT(11) UNSIGNED NOT NULL DEFAULT '0', CHANGE `owner` `owner` INT(11) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE prefix_aks CHANGE `ankunft` `ankunft` INT(11) NULL DEFAULT NULL, CHANGE `galaxy` `galaxy` TINYINT(3) UNSIGNED NULL DEFAULT NULL, CHANGE `system` `system` SMALLINT(5) UNSIGNED NULL DEFAULT NULL, CHANGE `planet` `planet` TINYINT(3) UNSIGNED NULL DEFAULT NULL, CHANGE `planet_type` `planet_type` ENUM('1', '3') NULL DEFAULT NULL;
ALTER TABLE prefix_alliance CHANGE `id` `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, CHANGE `ally_owner` `ally_owner` INT(11) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE prefix_statpoints DROP INDEX `id_owner_2`; /* Del this Query, if this Query give a error */