<?php

$LNG['faq']			= array(
"<font size=3>Zgrade</font>" => "Prva stvar koju trebate napraviti u igri je izgradnja zgrada. To su Rudnik metala, Rudnik kristala, deuterija i sintesajzer. Oni ce dati sve resurse kako bi izgradili svoje carstvo i tako ih nadogradivati na visok nivo.Svaki od tih objekata treba energiju za rad, i ako vasa proizvodnja energije postaje manja od unosa ovih triju struktura, oni nece obaviti posao. Prije nadogradnje zgrade, uvijek mozete kliknuti na sliku sama zgrada i vidjeti koliko ce vise energije zahtijevati sljedeca razina. Opet, to je izuzetno bitno da nadogradite te strukture sto je brze moguce. Oni su direktno proporcionalni kako brzo mozete unaprijed u igri. ",
"" => "Drugi prioritet u izgradnji su objekti koji ne zahtijevaju energiju za rad. Naime, oni ne uzimaju viska energije koje imate. To su Tvornica robota, Brodogradiliste i Centar za istrazivanje. Nove gradevine opcija ce se pojaviti nakon sto ste dostigli zahtjeve da ih stvorite.Na primjer, to je uvjet da imaju razinu 2 Tvornica robota prije nego sto mozete izgraditi brodogradiliste. Visa razina Tvornica robota brze mozete nadograditi svoje zgrade i graditi brodove. Razina brodogradilista sama djelomicno odreduje koje brodove ili obrambene jedinice mozete stvoriti. Koje brodove ili obrambene jedinice mozete napraviti ako ste istrazili odgovarajucu razinu tehnologije za svaki u istrazivackom laboratoriju. To nas dovodi do sljedeceg odjeljka, tehnologija.",
"<font size=3>Tehnologija</font>" => "Tehnologija gumb na lijevom izborniku ce vam reci sve zahtjeve za istrazivanje bilo koje tehnologije i stvaranje bilo kakve izgradnje, brod ili obranu. Takoder detalje sto je potrebno kako bi se zaposlio bilo  koji oficir. Jednostavno mozete dobiti ideju o tome sto imate i sto je jos uvijek potrebno zelena(imas) / crvena(nemas) boja. Isto tako, mozete kliknuti na naziv bilo kojeg predmeta procitati detaljan opis stavke i sto je to. Koristite ovo cesto to ce biti dobra karta za vas da ostvarite ciljeve koje zelite napraviti u igri. Kada se nesto istrazuje neka tehnologija, svi istrazivacki centri na sve vase planete su u upotrebi, i ne mogu se nadograditi dok su u upotrebi.",
"<font size=3>Galaksija</font>" => "Ova opcija u glavnom izborniku je nacin da biste vidjeli kartu  oko vas u svemiru.Svaki planet ima odredenu adresu u prikazu karte. Adrese su polozene u X: Y: Z format, gdje je X = pojedinacna galaksije, Y = Suncev sustav, te Z = orbitalni utor u odnosu na zvijezde. Orbitalni slotovi su 1-15 gdje je utor jedan(1) najblize zvijezdi, utor 15 je najudaljeni (ovo je dobro znati prilikom izgradnje solarnih satelita, oni su blizi suncu, veci njihov izlaz energije.) Tu je i utor za rezervirana 16. posebno za ono sto cemo raspraviti u sljedecem odjeljku, crna materija i ekspedicija.",
"<font size=3>Crna Materija</font>" => "Crna Materija se dobiva kroz pohode na prostranstvo prostor(16) u kojem saljete svoje flote. Koristi se za uposljavanje oficira. Astrofizika mora se istrazivati u laboratoriju, a tu je zaista dobar dio rizika koji su ukljuceni s slanjem brodova na njima. Isto tako, postoje i druge moguce nagrade osim crne materije. Na primjer, mozete se susresti sa strancima, gusari, ili cak crne rupe i izgubiti neke ili sve svoje brodove.Susret napustenih brodova i vratiti se kuci s visebrojnom flotom nego sto ste se krenuli. Takoder, potencijalne nagrade proporcionalno se povecava s velicinom flote koju saljete,ekspedicije su mudri nacin da se ide naprijed u igri, uglavnom zbog cinjenice da su oficir strahovito vrijedni.",
"<font size=3>Oficiri</font>" => "Oficiri ce zaista povecati vase mogucnosti i pomoci da rastete brze u igri sa bodovima. Ne mogu dovoljno naglasiti cinjenicu da bi trebali slati ekspedicije cijelo vrijeme non-stop dok ne dotignete max.level za svakoga.Oni mogu uciniti stvari kao sto je dvostruki iznos resursa po satu.Daje sposobnost za stvaranje jakih brodova u igri. Na tehnologija stranici, mozete kliknuti svaki casnik i vidjeti sto su njihove pojedinacne prednosti, kao i one koje treba zaposliti kako bi otkljucali druge.",
"<font size=3>Resursi</font>" => "Resursi pregled ce vam pokazati proizvodnje od svakog od resursa na sat / dan / tjedan, kao i vasu energiju. Ovo je mjesto gdje mozete birati prema dolje postotak proizvodnje ovo se koristi ukoliko nemate dovoljno energije. ",
"<font size=3>Trgovac</font>" => "Trgovac je zaista neprocjenjiv. Ovdje mozete razmjenjivati jedan resurs za drugi izmedu Metal, Kristal, i deuterija. Tecaja Metal, Kristal, i deuterija je 4/2/1.",
"<font size=3>Obrana/Brodogradiliste</font>" => "Ja grupiram ta dva ekrana zajedno jer su vrlo slicni kao sto cete vidjeti u igri. Oni oboje zahtijevaju brodogradilista i da ce koristiti isti red cekanja za izgradnju. Obrana je mjesto gdje mozete izgraditi planetarnu obranu. Klikom na sliku neke obrambene jedinice opcija ce vam reci statistike kao sto su koliko bodova ima hit, napad snaga, stit snage, itd.Brodogradiliste je slicno klikom na sliku svakog broda ce vam reci individualne statistike. ",
"<font size=3>Borba</font>"	=> "U borbi postoje dvije strane: napadacka i braniteljeva. Postoji sansa da je napadac poslao flotu na planetu gdje nema obrane ni flote pa je u tom slucaju automatski pobijedio. Ali ako branitelj ima brodova na planetu onda ce svaka strana pucati na neprijatelja.Na kraju bitke unisteni brodovi i obrana plutaju u polju olupina oko planeta na kojem se dogodila bitka.",
"" => "Da bi razumjeli kako bitka funkcionira morate znati da svaka jedinica ima tri osnovna parametra koja su osnovna u borbi: vrijednost napada, jacina stitova i omot. Postoji i cetvrti parametar, udarna moc, ali nije toliko vazan za osnovno shvacanje bitke.
U svakoj rundi, sve jedinice koje sudjeluju u borbi pucaju slucajnim odabirom na neprijatelja. steta koju nanose je jednaka vrijednosti napada svih jedinica, ali prije se oduzme od jacine stita neprijateljske jedinice. Ako stit dostigne nulu onda ono sto je ostalo od napada ide na omot. Na kraju runde jedinice koje su primile stetu na omot vise od 30% imaju da eksplodiraju. Jedinicama koje prezive ce se stit obnoviti.
Nakon borbe obrambene jedinice imaju 70% sanse da ce se obnoviti.",
"<font size=3>Koloniziranje</font>" => "Koloniziranje je zadatak na koji saljete kolonijalni brod na praznu poziciju u solarnom sistemu sa ciljem osnivanja nove kolonije. Ukoliko netko kolonizira tu poziciju prije vas, vas kolonijalni brod vraca se na planetu s koje je krenuo.
Upozorenje #1: uz glavni planet moguce je imati najvise 9 kolonija!

Kada uspjesno kolonizirate planetu na njoj cete zateci 500 metala i 500 kristala.

Upozorenje #2: svi resursi koje stavite u kolonijalni brod biti ce izgubljeni stoga ostavite polja za resurse prazna kada saljete kolonijalni brod!
Nakon kolonizacije mozete na novoosnovanu koloniju poslati transportere sa resursima kako bi izgradili svoju novu koloniju. Za sto brzu izgradnju kolonije preporuca se slanje sljedeceg omjera resursa:
Odnos - Metal:Kristal:Deuterij - 11:4:2 . ",

"<font size=2>Imate jos pitanja? Posaljite mi PM ili otvorite novi tiket u izborniku (Pitanja).</font>" => "",
);

$LNG['faq_overview']	= "Vodic za pocetnike";
?>