<style>th.u{border:0px;font-weight:600;}</style>
<tr>
	<th>{Id}</th>
	<th>{Fleet}</th>
	<th>{Mission}</th>
	<th>{St_Owner}</th>
	<th>{St_Posit}</th>
	<th>{St_Time}</th>
	<th>{En_Owner}</th>
	<th>{En_Posit}</th>
	<th>{En_Time}</th>
    <th>{Wa_Time}</th>
</tr>